export const tables = {
    HABITACION: 'HABITACION',
    HABITACION_MOVIM: 'HABITACION_MOVIM',
    PEDIDO_WEB: 'PEDIDO_WEB',
    PEDIDO_WEB_DETALLE: 'PEDIDO_WEB_DETALLE',
    PEDIDOS: 'PEDIDOS',
    PEDIDOS_DETALLE: 'PEDIDOS_DETALLE',
    TERCEROS: 'TERCEROS',
    ARTICULO: 'ARTICULO',
    LISTA_PRECIOS: 'LISTA_PRECIOS',
    PRECIOS_ARTICULO: 'PRECIOS_ARTICULO',
    CLIENTES: 'CLIENTES',
    PREFIJOS: 'PREFIJOS',
    BODEGAS: 'BODEGAS',
    ZONAS: 'ZONAS',
    FORMAS_PAGO: 'FORMAS_PAGO',
    RECIBOS_CAJA: 'RECIBOS_CAJA',
    RECIBOS_CAJA_PAGO: 'RECIBOS_CAJA_PAGO',
    ANTICIPOS_CLIENTE: 'ANTICIPOS_CLIENTE',
    RECIBOS_CAJA_DETALLE: 'RECIBOS_CAJA_DETALLE',
    HABITACION_MOVIM_ANTICIPOS: 'HABITACION_MOVIM_ANTICIPOS',
    FACTURA_WEB: 'FACTURA_WEB',
    FACTURA_WEB_DETALLE: 'FACTURA_WEB_DETALLE',
    FACTURAS: 'FACTURAS',
    FACTURAS_DETALLE: 'FACTURAS_DETALLE',
    DOC_INVENTARIO_WEB: 'DOC_INVENTARIO_WEB',
    DOC_INVENTARIO_DET_WEB: 'DOC_INVENTARIO_DET_WEB',
    REMISIONES_VENTA: 'REMISIONES_VENTA',
    REMISIONES_VENTA_DETALLE: 'REMISIONES_VENTA_DETALLE',
    PUNTO_VENTA: 'PUNTO_VENTA',
    BODEGA: 'BODEGA',
    TIPO_ID: 'TIPO_ID',
    CIUDADES: 'CIUDADES'
};




