/* ========================================================
   SCRIPT DDL OFICIAL DE MIGRACIÓN PARA BASE DE DATOS EMP
   Archivo: C:\SYSplus2025\Datos\EMP\SYSPLUS.FDB
   ======================================================== */

-- 1. TABLA HABITACION
-- Tabla de habitacion para realizar el crud
CREATE TABLE HABITACION (
    ID_HABITACION        VARCHAR(20) NOT NULL PRIMARY KEY,
    NUMERO               VARCHAR(20) NOT NULL,
    ESTADO               VARCHAR(30) DEFAULT 'Disponible' NOT NULL,
    TIPO                 VARCHAR(50),
    PISO                 INTEGER DEFAULT 1,
    NOTAS                VARCHAR(250),
    ARTI_COD             VARCHAR(15),
    CARACTERISTICAS      VARCHAR(250),
);

-- 2. TABLA HABITACION_MOVIM
CREATE TABLE HABITACION_MOVIM (
    ID_MOVIM       INTEGER NOT NULL,
    ID_HABITACION  VARCHAR(20) NOT NULL,
    ID_DOC         INTEGER,
    FECHA_RESERVA  VARCHAR(50),
    FECHA_SALIDA   VARCHAR(50),
    DINW_ID        INTEGER,
    ESTADO         VARCHAR(30) DEFAULT 'Activo',
    ANCL_ID        INTEGER,
    TIPO           INTEGER
);

CREATE TABLE HABITACION_MOVIM_ANTICIPOS (
    ID_MOVIM_ANT   INTEGER NOT NULL,
    ID_MOVIM       INTEGER NOT NULL,
    ANCL_ID        INTEGER NOT NULL,
    ITEM_ID        INTEGER NOT NULL,
)

-- 3. INSERTAR HABITACIONES BASE (101 a 302)
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('1', '001', '101', 'Disponible', 'DOBLE', 1, 120000, 'TV, NEVERA, JACUZZI');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('2', '001', '102', 'Disponible', 'DOBLE', 1, 120000, 'TV, NEVERA, JACUZZI');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('3', '001', '201', 'Disponible', 'SENCILLA', 2, 90000, 'TV, NEVERA');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('4', '001', '202', 'Disponible', 'SENCILLA', 2, 90000, 'TV, NEVERA');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('5', '001', '203', 'Disponible', 'DOBLE', 2, 120000, 'TV, NEVERA, JACUZZI');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('6', '001', '204', 'Disponible', 'DOBLE', 2, 120000, 'TV, NEVERA, JACUZZI');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('7', '001', '301', 'Disponible', 'FAMILIAR', 3, 180000, 'TV, NEVERA, 2 CAMAS');
INSERT INTO HABITACION (ID_HABITACION, ARTI_COD, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, CARACTERISTICAS) VALUES ('8', '001', '302', 'Disponible', 'SENCILLA', 3, 90000, 'TV, NEVERA');
