CREATE TABLE PREFIJOS (
    TIDO_COD      INTEGER NOT NULL,
    PREF_PRE      VARCHAR(4) NOT NULL,
    PREF_ACTUAL   T_NUMDOC NOT NULL /* T_NUMDOC = VARCHAR(8) */,
    PREF_AUTO     T_BOOLEANO NOT NULL /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_IVAINC   T_BOOLEANO NOT NULL /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_PROY     VARCHAR(4),
    PREF_CENTRO   VARCHAR(4),
    PREF_ACTIVO   T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_USUARIO  T_USUARIO /* T_USUARIO = VARCHAR(10) */,
    TICO_COD      T_TIPO_COMP /* T_TIPO_COMP = CHAR(3) */,
    SUCU_ID       T_ID /* T_ID = INTEGER */,
    PREF_DEC1818  T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_EXISTE   T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_CONTADO  T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PREF_PRFAC    T_PREFIJO /* T_PREFIJO = VARCHAR(4) */
);

CREATE TABLE FORMAS_PAGO (
    FOPA_ID          T_ID NOT NULL /* T_ID = INTEGER */,
    FOPA_NOM         VARCHAR(30) NOT NULL,
    FOPA_CTACONTA    T_CTA_CONTABLE /* T_CTA_CONTABLE = VARCHAR(20) */,
    FOPA_CONSIGNA    T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    FOPA_CTABCO      T_ID /* T_ID = INTEGER */,
    FOPA_PREFBCO     VARCHAR(4),
    FOPA_TARJETA     VARCHAR(3),
    FOPA_CTANIIF     T_CTA_CONTABLE /* T_CTA_CONTABLE = VARCHAR(20) */,
    FOPA_MONEDAEX    T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    FOPA_CARTERA     T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    FOPA_DIAIVA      T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    FOPA_FRANQUICIA  T_DESCART /* T_DESCART = VARCHAR(300) */,
    FOPA_RECARGO     T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    FOPA_CODDIAN     VARCHAR(2) NOT NULL,
    FOPA_ACTIVO      T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    SUCU_ID          T_ID /* T_ID = INTEGER */,
    FOPA_NOMBREFE    T_CONCEPTO /* T_CONCEPTO = VARCHAR(60) */,
    FOPA_CONVCART    T_ID /* T_ID = INTEGER */
);


-- Registra encabezado
INSERT INTO RECIBOS_CAJA (RECA_ID, CAJA_ID, TIDO_COD, PREF_PRE, RECA_NUMERO, RECA_FECHA, RECA_CONC, RECA_MONTO, RECA_RTFTEMONTO, RECA_RTIVAMONTO, RECA_RTICAMONTO, RECA_DTOF, RECA_OBS, TERC_NIT, RECA_NOMTERC, RECA_ANULADO, RECA_TRANSMIT, COBR_COD, RECA_PROVISIONAL, RECA_PROVID, RECA_USUARIO, NUMOK, RECA_TRM, RECA_EXEDENTE, CONS_ID, RECA_PAGANOM, RECA_RTCREEM, RECA_PRESTAMO) VALUES (2471524, 1, 61, '0000', '000036', '18-AUG-2026', 'Ab. ANTICLIE 0000000001,', 10000, 0, 0, 0, 0, NULL, '1031144263', 'KEVINS', 'N', 'N', 1, NULL, NULL, 'SYSDBA', 'S', 1, 0, NULL, 'N', 0, NULL);
INSERT INTO RECIBOS_CAJA (RECA_ID, CAJA_ID, TIDO_COD, PREF_PRE, RECA_NUMERO, RECA_FECHA, RECA_CONC, RECA_MONTO, RECA_RTFTEMONTO, RECA_RTIVAMONTO, RECA_RTICAMONTO, RECA_DTOF, RECA_OBS, TERC_NIT, RECA_NOMTERC, RECA_ANULADO, RECA_TRANSMIT, COBR_COD, RECA_PROVISIONAL, RECA_PROVID, RECA_USUARIO, NUMOK, RECA_TRM, RECA_EXEDENTE, CONS_ID, RECA_PAGANOM, RECA_RTCREEM, RECA_PRESTAMO) VALUES (2471527, 1, 61, '0000', '000039', '20-AUG-2026', 'Ab. ANTICLIE 0000000003,', 20000, 0, 0, 0, 0, NULL, '1031144263', 'KEVINS', 'N', 'N', 1, NULL, NULL, 'SYSDBA', 'S', 1, 0, NULL, 'N', 0, NULL);
-- IDDOC = GEN_ID(id_recicaja, 1);
-- TIDO_COD = 61
-- RECA_NUMERO = PREFIJOS = PREF_ACTUAL + 1

-- Registra pago y forma de pago
INSERT INTO RECIBOS_CAJA_PAGO (RECA_ID, RCPA_ITEM, FOPA_ID, RCPA_BANCO, RCPA_CUENTA, RCPA_NUMERO, RCPA_FECHA, RCPA_MONTO, RCPA_ANULADO, RCPA_TRANSMIT, RCPA_IVAMONTO, RCPA_CONC, RCPA_TRM) VALUES (2471524, 1, 1, '', '', '', '18-AUG-2026', 10000, 'N', 'N', 0, 'Ab. ANTICLIE 0000000001,', 1);
INSERT INTO RECIBOS_CAJA_PAGO (RECA_ID, RCPA_ITEM, FOPA_ID, RCPA_BANCO, RCPA_CUENTA, RCPA_NUMERO, RCPA_FECHA, RCPA_MONTO, RCPA_ANULADO, RCPA_TRANSMIT, RCPA_IVAMONTO, RCPA_CONC, RCPA_TRM) VALUES (2471527, 1, 4, '98', '9999', '000009', '20-AUG-2026', 20000, 'N', 'N', 0, 'Ab. ANTICLIE 0000000003,', 1);
-- FOPA_ID = FORMAS_PAGO
-- RCPA_BANCO, RCPA_CUENTA, RCPA_NUMERO = si la forma esta con el campo FOPA_CONSIGNA = 'S'
-- se debe consultar los datos para traer los tres campos (RCPA_BANCO, RCPA_CUENTA, RCPA_NUMERO)

-- este es un ejemplo que se tiene en cloud:
--     findOneNumero = async (id: string, knex: Knex) => {
--         const res = await knex()
--             .first()
--             .fromRaw(`${tables.RECIBOS_CAJA_PAGO} as rcj`)
--             .joinRaw(
--                 `join ${tables.FORMAS_PAGO} fp on rcj.FOPA_ID = fp.FOPA_ID`,
--             )
--             .where('rcj.FOPA_ID', id)
--             .orderBy('rcj.RECA_ID', 'desc');
--         return res;
--     };

-- retorna:
-- {
--     "RECA_ID": 1421,
--     "RCPA_ITEM": 1,
--     "FOPA_ID": 4,
--     "RCPA_BANCO": "99",
--     "RCPA_CUENTA": "9999",
--     "RCPA_NUMERO": "000749",
--     "RCPA_FECHA": "2026-08-19T00:00:00.000Z",
--     "RCPA_MONTO": 1246550,
--     "RCPA_ANULADO": "N",
--     "RCPA_TRANSMIT": "N",
--     "RCPA_IVAMONTO": 0,
--     "RCPA_CONC": "Ab. FACTVENT FES00001288, NOTACRCL NCC000061",
--     "RCPA_TRM": 1,
--     "FOPA_NOM": "CONSIGNACION",
--     "FOPA_CTACONTA": "11100501",
--     "FOPA_CONSIGNA": "S",
--     "FOPA_CTABCO": 1,
--     "FOPA_PREFBCO": "0000",
--     "FOPA_TARJETA": "",
--     "FOPA_CTANIIF": "",
--     "FOPA_MONEDAEX": null,
--     "FOPA_CARTERA": "N",
--     "FOPA_DIAIVA": "N",
--     "FOPA_FRANQUICIA": null,
--     "FOPA_RECARGO": 0,
--     "FOPA_CODDIAN": "42",
--     "FOPA_ACTIVO": "S",
--     "SUCU_ID": 0,
--     "FOPA_NOMBREFE": null,
--     "FECHA_CAMBIO": null
-- }


-- Registra anticipo
INSERT INTO ANTICIPOS_CLIENTE (ANCL_ID, TIDO_COD, PREF_PRE, TERC_NIT, ANCL_FECHA, ANCL_NUMERO, ANCL_CONC, ANCL_BASE, ANCL_IVAPORC, ANCL_IVAMONTO, ANCL_RTFTEPORC, ANCL_RTFTEMONTO, ANCL_RTIVAPORC, ANCL_RTIVAMONTO, ANCL_RTICAPORC, ANCL_RTICAMONTO, ANCL_DTOFECHA, ANCL_DTOFPORC, ANCL_DTOFMONTO, ANCL_ANULADO, ANCL_TRANSMIT, COBR_COD, ANCL_OBS, RECA_ID, ANCL_USUARIO, ANCL_SUCURSAL, NUMOK, VEND_COD, ANCL_TRM, ANCL_RTCREE, ANCL_RTCREEM, ANCL_PEDID, ANCL_PEDIDO, ANCL_DETCLI) VALUES (13572, 45, '0000', '1031144263', '18-AUG-2026', '000001', 'PRUEBAS', 10000, 0, 0, 0, 0, 0, 0, 0, 0, '18-AUG-2026', 0, 0, 'N', 'N', 1, NULL, 2471524, 'SYSDBA', '01', 'S', 1, 1, 0, 0, NULL, NULL, NULL);
INSERT INTO ANTICIPOS_CLIENTE (ANCL_ID, TIDO_COD, PREF_PRE, TERC_NIT, ANCL_FECHA, ANCL_NUMERO, ANCL_CONC, ANCL_BASE, ANCL_IVAPORC, ANCL_IVAMONTO, ANCL_RTFTEPORC, ANCL_RTFTEMONTO, ANCL_RTIVAPORC, ANCL_RTIVAMONTO, ANCL_RTICAPORC, ANCL_RTICAMONTO, ANCL_DTOFECHA, ANCL_DTOFPORC, ANCL_DTOFMONTO, ANCL_ANULADO, ANCL_TRANSMIT, COBR_COD, ANCL_OBS, RECA_ID, ANCL_USUARIO, ANCL_SUCURSAL, NUMOK, VEND_COD, ANCL_TRM, ANCL_RTCREE, ANCL_RTCREEM, ANCL_PEDID, ANCL_PEDIDO, ANCL_DETCLI) VALUES (13574, 45, '0000', '1031144263', '20-AUG-2026', '000003', 'ABONO RESERVA', 20000, 0, 0, 0, 0, 0, 0, 0, 0, '20-AUG-2026', 0, 0, 'N', 'N', 1, NULL, 2471527, 'SYSDBA', '01', 'S', 1, 1, 0, 0, NULL, NULL, NULL);
-- TIDO_COD = 45
-- ANCL_NUMERO = PREFIJOS = PREF_ACTUAL + 1
-- RECA_ID = id del recibo

-- Registra detalle
INSERT INTO RECIBOS_CAJA_DETALLE (RECA_ID, RCDE_ITEM, RCDE_TIPODOC, RCDE_IDDOC, RCDE_PREFIJO, RCDE_NUMERO, RCDE_ABONO, RCDE_RTFTE, RCDE_RTIVA, RCDE_RTICA, RCDE_DTOF, RCDE_ANULADO, RCDE_TRANSMIT, RCDE_COMIP, RCDE_SUCURSAL, RCDE_DIFCAMBIO, RCDE_COBR, RCDE_RCREE) VALUES (2471524, 1, 45, 13572, '0000', '000001', 10000, 0, 0, 0, 0, 'N', 'N', 'M', '01', 0, 1, 0);
INSERT INTO RECIBOS_CAJA_DETALLE (RECA_ID, RCDE_ITEM, RCDE_TIPODOC, RCDE_IDDOC, RCDE_PREFIJO, RCDE_NUMERO, RCDE_ABONO, RCDE_RTFTE, RCDE_RTIVA, RCDE_RTICA, RCDE_DTOF, RCDE_ANULADO, RCDE_TRANSMIT, RCDE_COMIP, RCDE_SUCURSAL, RCDE_DIFCAMBIO, RCDE_COBR, RCDE_RCREE) VALUES (2471527, 1, 45, 13574, '0000', '000003', 20000, 0, 0, 0, 0, 'N', 'N', 'M', '01', 0, 1, 0);
-- RCDE_TIPODOC = 45
-- RCDE_IDDOC = ANCL_ID
-- RCDE_PREFIJO, RCDE_NUMERO, RCDE_ABONO = datos del anticipo

