CREATE TABLE TURNO (
    ID_TURNO        INTEGER NOT NULL PRIMARY KEY,
    USUARIO         VARCHAR(30) NOT NULL,
    FECHA_APERTURA  TIMESTAMP NOT NULL,
    BASE            NUMERIC(15,2) DEFAULT 0 NOT NULL,
    FECHA_CIERRE    TIMESTAMP,
    ESTADO          VARCHAR(20) DEFAULT 'Abierto' NOT NULL, -- 'Abierto', 'Cerrado'
    TOTAL_VENTAS    NUMERIC(15,2) DEFAULT 0,
    TOTAL_PAGOS     NUMERIC(15,2) DEFAULT 0,
    OBSERVACIONES   VARCHAR(250)
);

CREATE TABLE TURNO_DET_PAGOS (
    ID_TURNO        INTEGER NOT NULL,
    ID_ITEM         INTEGER NOT NULL,
    FORMAP          INTEGER NOT NULL,
    NOMBRE_FORMA    VARCHAR(50),
    MONTO           NUMERIC(15,2) DEFAULT 0,
    PRIMARY KEY (ID_TURNO, ID_ITEM)
);

CREATE TABLE TURNO_DET_HABITACIONES (
    ID_TURNO        INTEGER NOT NULL,
    ID_ITEM         INTEGER NOT NULL,
    ID_HABITACION   VARCHAR(20) NOT NULL,
    NUMERO          VARCHAR(20),
    ESTADO          VARCHAR(30) NOT NULL,
    HUESPED         VARCHAR(100),
    TOTAL_PENDIENTE NUMERIC(15,2) DEFAULT 0,
    PRIMARY KEY (ID_TURNO, ID_ITEM)
);

CREATE TABLE TURNO_DET_FACTURAS (
    ID_TURNO        INTEGER NOT NULL,
    ID_ITEM         INTEGER NOT NULL,
    PREF            VARCHAR(10),
    FACTINI         INTEGER NOT NULL,
    FACTFIN         INTEGER NOT NULL,
    CANTIDAD        INTEGER DEFAULT 0,
    TOTAL           NUMERIC(15,2) DEFAULT 0,
    PRIMARY KEY (ID_TURNO, ID_ITEM)
);