CREATE TABLE H_INTERFAZ_PREFIJOS (
    TIPO_DOC     INTEGER,
    TIPO_NOM     VARCHAR(60),
    PREF_PRE     VARCHAR(4),
    NOMBRE_INT   VARCHAR(60),
    ID_INTERFAZ  INTEGER
);


INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (31, 'FE', 'FE', 'INTERFAZ_VENTAS', 4);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (31, 'REMISION', '0000', 'INTERFAZ_VENTAS', 1);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (61, 'RC_CARTERA', 'FE', 'INTERFAZ_CAJA', 9);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (61, 'RC_ANTICIPO', 'FE', 'INTERFAZ_CAJA', 10);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (61, 'RC_CARTERA', '0000', 'INTERFAZ_CAJA', 1);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (61, 'RC_ANTICIPO', '0000', 'INTERFAZ_CAJA', 8);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (43, 'APL_REMISION', '0000', 'CONTABIL_APLICACL', 4);
INSERT INTO H_INTERFAZ_PREFIJOS (TIPO_DOC, TIPO_NOM, PREF_PRE, NOMBRE_INT, ID_INTERFAZ)
                         VALUES (43, 'APL_FE', 'FE', 'CONTABIL_APLICACL', 5);