CREATE TABLE ARTICULO (
    ARTI_COD          T_COD_ARTICULO NOT NULL /* T_COD_ARTICULO = VARCHAR(15) */,
    GRUP_COD          VARCHAR(2),
    SUBG_COD          VARCHAR(3),
    MARC_COD          VARCHAR(3),
    ARTI_DES          T_NOMLARGO NOT NULL /* T_NOMLARGO = VARCHAR(300) */,
    ARTI_DESVAR       T_BOOLEANO NOT NULL /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    ARTI_TIPO         CHAR(1) NOT NULL,
    ARTI_EXIST        CHAR(1) NOT NULL,
    ARTI_FECHA        DATE,
    ARTI_UNIDAD       VARCHAR(8) NOT NULL,
    ARTI_PRECIO       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    ARTI_DIAS         INTEGER,
    ESAR_COD          CHAR(1),
    ARTI_USUARIO      T_USUARIO /* T_USUARIO = VARCHAR(10) */,
    TAIV_COD          T_ID NOT NULL /* T_ID = INTEGER */,
    ARTI_CLASE        CHAR(1),
    ARTI_DIANALIS     INTEGER,
    ARTI_DESCORTA     VARCHAR(30),
    ARTI_TIENDA       T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    ARTI_CAMBPRECIVA  T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    ARTI_ORDEN        ENTERO /* ENTERO = SMALLINT */,
    ARTI_EVEXIS       T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    FABR_COD          T_SUBGRUPO /* T_SUBGRUPO = VARCHAR(3) */
);

CREATE TABLE LISTA_PRECIOS (
    LIPR_COD        T_ID NOT NULL /* T_ID = INTEGER */,
    LIPR_NOM        VARCHAR(30) NOT NULL,
    LIPR_COMI       T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_DIASMAX    INTEGER,
    LIPR_FECINI     DATE,
    LIPR_FECFIN     DATE,
    LIPR_MARGEN     T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_UTIL       T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_COMIMONTO  T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    LIPR_MODIF      T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    SUCU_ID         T_ID /* T_ID = INTEGER */,
    LIPR_AUTO       T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    LIPR_DIASEM     SMALLINT,
    LIPR_HORAINI    TIME,
    LIPR_HORAFIN    TIME,
    LIPR_DSCTO      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_PREDET     T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    LIPR_DTOF1      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_DTOF1DIAS  ENTERO /* ENTERO = SMALLINT */,
    LIPR_DTOF2      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_DTOF2DIAS  ENTERO /* ENTERO = SMALLINT */,
    LIPR_DTOF3      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_DTOF3DIAS  ENTERO /* ENTERO = SMALLINT */,
    LIPR_DTOF4      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    LIPR_DTOF4DIAS  ENTERO /* ENTERO = SMALLINT */,
    LIPR_GRUPLIS    T_CONCEPTO /* T_CONCEPTO = VARCHAR(60) */,
    LIPR_MAX        T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    LIPR_MIN        T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    LIPR_REDON      ENTERO /* ENTERO = SMALLINT */
);

CREATE TABLE PRECIOS_ARTICULO (
    LIPR_COD        T_ID NOT NULL /* T_ID = INTEGER */,
    ARTI_COD        T_COD_ARTICULO NOT NULL /* T_COD_ARTICULO = VARCHAR(15) */,
    PRAR_FIJO       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PRAR_AUTO       T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PRAR_ESCALAS    T_BOOLEANO /* T_BOOLEANO = CHAR(1) check (value in ('S','N')) */,
    PRAR_LISTABASE  T_ID /* T_ID = INTEGER */,
    PRAR_FACTORLB   T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PRAR_NOMBRE     T_CONCEPTO /* T_CONCEPTO = VARCHAR(60) */
);

CREATE TABLE PEDIDO_WEB (
    PEWE_ID           T_ID NOT NULL /* T_ID = INTEGER */,
    PEWE_FECHA        FECHA /* FECHA = DATE */,
    TERC_NIT          T_NIT /* T_NIT = VARCHAR(20) */,
    PEWE_SUCURSAL     VARCHAR(10),
    PEWE_OBS          BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PEWE_ENTREGA      FECHA /* FECHA = DATE */,
    PEWE_DIASCR       INTEGER,
    VEND_COD          T_ID /* T_ID = INTEGER */,
    PEWE_DTOPORC      T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWE_ADICIONAL    T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWE_EXTRA        T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWE_IVAMONTO     T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWE_TOTAL        T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWE_RTFTEPORC    T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWE_RTIVAPORC    T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWE_RTICAPORC    T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWE_PREF         VARCHAR(4),
    PEWE_DTOMONTO     T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWE_NUMPED       PREF_NUM /* PREF_NUM = VARCHAR(12) */,
    PEWE_IDPED        T_ID /* T_ID = INTEGER */,
    PEWE_NOMCLI       T_CONCEPTO /* T_CONCEPTO = VARCHAR(60) */,
    PTVT_ID           T_ID /* T_ID = INTEGER */,
    PEWE_EVENTO       T_ID /* T_ID = INTEGER */,
    PEWE_AUTOCAR      T_ID /* T_ID = INTEGER */,
    PEWE_AUTOCUPO     T_ID /* T_ID = INTEGER */,
    PEWE_TIPOENTREGA  INTEGER,
    PEWE_HORAENTREGA  TIME,
    PEWE_IDOFFLINE    T_ID /* T_ID = INTEGER */,
    PEWE_LATITUD      T_TELEFONO /* T_TELEFONO = VARCHAR(40) */,
    PEWE_LONGITUD     T_TELEFONO /* T_TELEFONO = VARCHAR(40) */,
    PEWE_ANULADO      BOOLEANO /* BOOLEANO = CHAR(1) */
);

CREATE TABLE PEDIDO_WEB_DETALLE (
    PEWE_ID          T_ID NOT NULL /* T_ID = INTEGER */,
    PEWD_ITEM        T_ID NOT NULL /* T_ID = INTEGER */,
    ARTI_COD         T_COD_ARTICULO /* T_COD_ARTICULO = VARCHAR(15) */,
    PEWD_CODBAR      T_BARRAS /* T_BARRAS = VARCHAR(50) */,
    BODE_COD         VARCHAR(2),
    PEWD_CANT        T_CANTIDAD /* T_CANTIDAD = NUMERIC(18,4) */,
    PEWD_UNIDAD      T_UNIDAD /* T_UNIDAD = VARCHAR(8) */,
    PEWD_FACTOR      T_CANTIDAD /* T_CANTIDAD = NUMERIC(18,4) */,
    LIPR_COD         T_ID /* T_ID = INTEGER */,
    PEWD_PRUNIT      T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_DTOP        T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWD_DTO1        T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWD_DTO2        T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWD_DTO3        T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWD_IVAP        T_PORCENTAJE /* T_PORCENTAJE = NUMERIC(9,4) DEFAULT 0 */,
    PEWD_IVAMONTO    T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_CONSUMO     T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_TOTAL       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_REFERENCIA  T_CONCEPTO /* T_CONCEPTO = VARCHAR(60) */,
    PEWD_DTOM        T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_DTO1M       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_DTO2M       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_DTO3M       T_MONTO /* T_MONTO = NUMERIC(18,2) DEFAULT 0 */,
    PEWD_DESC        T_NOMLARGO /* T_NOMLARGO = VARCHAR(300) */,
    PEWD_ANULADO     BOOLEANO /* BOOLEANO = CHAR(1) */
);

-- Tabla de habitacion para realizar el crud
CREATE TABLE HABITACION (
    ID_HABITACION        VARCHAR(20) NOT NULL PRIMARY KEY,
    NUMERO               VARCHAR(20) NOT NULL,
    ESTADO               VARCHAR(30) DEFAULT 'Disponible' NOT NULL,
    TIPO                 VARCHAR(50),
    PISO                 INTEGER DEFAULT 1,
    NOTAS                VARCHAR(250),
    ARTI_COD             VARCHAR(15),
    CARACTERISTICAS      VARCHAR(250),
);

-- tabla del movimiento de las habitaciones para llevar el control de fechas
CREATE TABLE HABITACION_MOVIM (
    ID_MOVIM       INTEGER NOT NULL,
    ID_HABITACION  VARCHAR(20) NOT NULL,
    PEDI_ID        INTEGER,
    ANCL_ID        INTEGER,
    FECHA_RESERVA  VARCHAR(50),
    FECHA_SALIDA   VARCHAR(50),
    PEWE_ID        INTEGER,
    ESTADO         VARCHAR(30) DEFAULT 'Activo'    
);

-- insert para iniciar
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('1', '101', 'Disponible', 'SENCILLA', 1, 0, NULL, 'TV, Aire Acondicionado, Wi-Fi', '101');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('2', '102', 'Disponible', 'DOBLE', 1, 0, NULL, 'TV, Aire Acondicionado, Wi-Fi', '102');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('3', '201', 'Disponible', 'SENCILLA', 2, 0, NULL, 'TV, Aire Acondicionado, Wi-Fi', '201');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('4', '202', 'Disponible', 'MATRIMONIAL', 2, 0, '', 'TV, Aire Acondicionado, Wi-Fi', '202');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('5', '203', 'Disponible', 'DOBLE', 2, 0, '', 'TV, Aire Acondicionado, Wi-Fi', '203');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('6', '204', 'Disponible', 'SENCILLA', 2, 0, '', 'TV, Aire Acondicionado, Wi-Fi', '204');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('7', '301', 'Disponible', 'FAMILIAR', 3, 0, '', 'TV, Aire Acondicionado, Wi-Fi', '301');
INSERT INTO HABITACION (ID_HABITACION, NUMERO, ESTADO, TIPO, PISO, PRECIO_NOCHE, NOTAS, CARACTERISTICAS, ARTI_COD) VALUES ('8', '302', 'Disponible', 'PREMIUM', 1, 0, '', 'TV, Aire Acondicionado, Wi-Fi', '302');